version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: malta-rek-cms
    ports:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data
